 subroutine error4()
!^^^^^^^^^^ (font-lock-keyword-face f90-ts-font-lock-error-face)
!          ^ (f90-ts-font-lock-error-face)
!           ^^^^^^ (font-lock-function-name-face f90-ts-font-lock-error-face)
!                 ^^ (f90-ts-font-lock-bracket-face f90-ts-font-lock-error-face)
      x = x + y
!^^^^^^^ (f90-ts-font-lock-error-face)
!       ^ (f90-ts-font-lock-operator-face f90-ts-font-lock-error-face)
!        ^^^ (f90-ts-font-lock-error-face)
!           ^ (f90-ts-font-lock-operator-face f90-ts-font-lock-error-face)
!            ^^ (f90-ts-font-lock-error-face)
      call foo()
!^^^^^ (f90-ts-font-lock-error-face)
!     ^^^^ (font-lock-keyword-face f90-ts-font-lock-error-face)
!         ^ (f90-ts-font-lock-error-face)
!          ^^^ (font-lock-function-name-face f90-ts-font-lock-error-face)
!             ^^ (f90-ts-font-lock-bracket-face f90-ts-font-lock-error-face)
      call bar(
!^^^^^ (f90-ts-font-lock-error-face)
!     ^^^^ (font-lock-keyword-face f90-ts-font-lock-error-face)
!         ^^^^ (f90-ts-font-lock-error-face)
!             ^ (f90-ts-font-lock-bracket-face f90-ts-font-lock-error-face)
